/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BackTop: typeof import('./../components/BackTop.vue')['default']
    Carousel: typeof import('./../components/Carousel/index.vue')['default']
    CategoryNode: typeof import('./../components/CategoryTreeSelector/CategoryNode.vue')['default']
    CategoryTreeSelector: typeof import('./../components/CategoryTreeSelector/index.vue')['default']
    ProductCard: typeof import('./../components/ProductCard.vue')['default']
    Readme: typeof import('./../components/Carousel/readme.md')['default']
    README: typeof import('./../components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheFooter: typeof import('./../components/TheFooter.vue')['default']
    TheHeader: typeof import('./../components/TheHeader.vue')['default']
    ToggleLocale: typeof import('./../components/ToggleLocale.vue')['default']
    ToggleTheme: typeof import('./../components/ToggleTheme.vue')['default']
  }
}
